#!/usr/bin/env ruby
def run_and_echo(cmd)
  puts cmd
  result = system(cmd)
  raise "FAIL - `#{cmd}`" unless result
end

max_steps = ARGV[0].to_i

begin
  branches = `git branch`.split("\n").map(&:strip)
  selected_branch_idx = branches.index { |b| b.start_with?('* ') }
  raise 'No branch selected!' unless selected_branch_idx

  selected_branch = branches[selected_branch_idx][2..-1]
  hit = selected_branch.match(
    %r{^(?<branch_prefix>(feature|hotfix)/[a-z\-]+)(?<branch_no>\d\d)}
  )
  raise "#{selected_branch} is not a chained branch" unless hit

  branch_prefix = hit[:branch_prefix]
  branch_no = hit[:branch_no].to_i

  previous_branch = selected_branch
  current_branch_no = branch_no

  run_and_echo("git push -f origin #{previous_branch}")

  next_branch = branches[selected_branch_idx + 1]
  current_branch_prefix = format("#{branch_prefix}%02i", current_branch_no + 1)
  return unless next_branch.start_with?(current_branch_prefix)

  run_and_echo(
    'git rebase ' \
    "--onto #{previous_branch} #{next_branch}~1 #{next_branch}"
  )
rescue StandardError => e
  STDERR.puts "\033[31m#{e}\033[0m"
  exit 1
end
