#!/usr/bin/env ruby
def run_and_echo(cmd)
  puts cmd
  result = system(cmd)
  raise "FAIL - `#{cmd}`" unless result
end

begin
  branches = `git branch`.split("\n").map(&:strip)
  selected_branch_idx = branches.index { |b| b.start_with?('* ') }
  raise 'No branch selected!' unless selected_branch_idx

  selected_branch = branches[selected_branch_idx][2..-1]
  hit = selected_branch.match(
    %r{^(?<branch_prefix>(feature|hotfix)/[a-z\-]+)(?<branch_no>\d\d)}
  )
  raise "#{selected_branch} is not a chained branch" unless hit

  branch_prefix = hit[:branch_prefix]
  branch_no = hit[:branch_no].to_i

  prev_branch_no = branch_no - 1
  prev_branch_prefix = format("#{branch_prefix}%02i", prev_branch_no)
  prev_branch_idx = branches.index { |b| b.start_with?(prev_branch_prefix) }
  raise 'Prev branch does not exist!' unless prev_branch_idx

  run_and_echo("git checkout #{branches[prev_branch_idx]}")
rescue StandardError => e
  STDERR.puts "\033[31m#{e}\033[0m"
  exit 1
end
